apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
        - name: frontend
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_4e3ff76bf9b6
          # env: 
          #     - name: REACT_APP_BASE_URL
          #       valueFrom:
          #         secretKeyRef: 
          #           name: my-secret
          #           key: react-app-base-url
          #     - name: REACT_APP_API_URL
          #       valueFrom:
          #         secretKeyRef: 
          #           name: my-secret
          #           key: react-app-api-url
          #     - name: REACT_APP_KAKAO_API_KEY
          #       valueFrom:
          #         secretKeyRef: 
          #           name: my-secret
          #           key: react-app-kakao-api-key
          #     - name: REACT_APP_KAKAO_REDIRECT_URI
          #       valueFrom:
          #         secretKeyRef: 
          #           name: my-secret
          #           key: react-app-kakao-redirect-uri
          #     - name: REACT_APP_JWT_SECRET
          #       valueFrom:
          #         secretKeyRef: 
          #           name: my-secret
          #           key: react-app-jwt-secret
          volumeMounts:
            - name: secret-volume
              mountPath: /app/.env
              subPath: .env
              
      volumes:
        - name: secret-volume
          secret:
            secretName: front-secret
          
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000